// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Tesla.ItcastCater.UIMap.LoginPageUIClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class LoginPageUI
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinEdit uITxtNameEdit = this.UI登陆Window.UITxtNameWindow.UITxtNameEdit;
            WinEdit uITxtPwdEdit = this.UI登陆Window.UITxtPwdWindow.UITxtPwdEdit;
            WinButton uI登陆Button = this.UI登陆Window.UI登陆Window1.UI登陆Button;
            #endregion

            // Type 'admin' in 'txtName' text box
            uITxtNameEdit.Text = this.RecordedMethod1Params.UITxtNameEditText;

            // Type '{Tab}' in 'txtName' text box
            Keyboard.SendKeys(uITxtNameEdit, this.RecordedMethod1Params.UITxtNameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'txtPwd' text box
            Keyboard.SendKeys(uITxtPwdEdit, this.RecordedMethod1Params.UITxtPwdEditSendKeys, true);

            // Click '登陆' button
            Mouse.Click(uI登陆Button, new Point(33, 26));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UI登陆Window UI登陆Window
        {
            get
            {
                if ((this.mUI登陆Window == null))
                {
                    this.mUI登陆Window = new UI登陆Window();
                }
                return this.mUI登陆Window;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UI登陆Window mUI登陆Window;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'admin' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditText = "admin";
        
        /// <summary>
        /// Type '{Tab}' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'txtPwd' text box
        /// </summary>
        public string UITxtPwdEditSendKeys = "nAI/+1YbLXAzMC+MylAiumF+gga6bwns";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UI登陆Window : WinWindow
    {
        
        public UI登陆Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "登陆";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("登陆");
            #endregion
        }
        
        #region Properties
        public UITxtNameWindow UITxtNameWindow
        {
            get
            {
                if ((this.mUITxtNameWindow == null))
                {
                    this.mUITxtNameWindow = new UITxtNameWindow(this);
                }
                return this.mUITxtNameWindow;
            }
        }
        
        public UITxtPwdWindow UITxtPwdWindow
        {
            get
            {
                if ((this.mUITxtPwdWindow == null))
                {
                    this.mUITxtPwdWindow = new UITxtPwdWindow(this);
                }
                return this.mUITxtPwdWindow;
            }
        }
        
        public UI登陆Window1 UI登陆Window1
        {
            get
            {
                if ((this.mUI登陆Window1 == null))
                {
                    this.mUI登陆Window1 = new UI登陆Window1(this);
                }
                return this.mUI登陆Window1;
            }
        }
        #endregion
        
        #region Fields
        private UITxtNameWindow mUITxtNameWindow;
        
        private UITxtPwdWindow mUITxtPwdWindow;
        
        private UI登陆Window1 mUI登陆Window1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtNameWindow : WinWindow
    {
        
        public UITxtNameWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtName";
            this.WindowTitles.Add("登陆");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtNameEdit
        {
            get
            {
                if ((this.mUITxtNameEdit == null))
                {
                    this.mUITxtNameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtNameEdit.WindowTitles.Add("登陆");
                    #endregion
                }
                return this.mUITxtNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtNameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtPwdWindow : WinWindow
    {
        
        public UITxtPwdWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtPwd";
            this.WindowTitles.Add("登陆");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtPwdEdit
        {
            get
            {
                if ((this.mUITxtPwdEdit == null))
                {
                    this.mUITxtPwdEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtPwdEdit.WindowTitles.Add("登陆");
                    #endregion
                }
                return this.mUITxtPwdEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtPwdEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UI登陆Window1 : WinWindow
    {
        
        public UI登陆Window1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnLogin";
            this.WindowTitles.Add("登陆");
            #endregion
        }
        
        #region Properties
        public WinButton UI登陆Button
        {
            get
            {
                if ((this.mUI登陆Button == null))
                {
                    this.mUI登陆Button = new WinButton(this);
                    #region Search Criteria
                    this.mUI登陆Button.SearchProperties[WinButton.PropertyNames.Name] = "登陆";
                    this.mUI登陆Button.WindowTitles.Add("登陆");
                    #endregion
                }
                return this.mUI登陆Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUI登陆Button;
        #endregion
    }
}
